In [101]:
"""
Created on Mon Sep 25 12:21:40 2017

@author: auredt7892
"""
import requests
import pandas as pd
from bs4 import BeautifulSoup

def getSoupFromURL(url, method='get', data={}):

  if method == 'get':
    res = requests.get(url)
  elif method == 'post':
    res = requests.post(url, data=data)
  else:
    return None

  if res.status_code == 200:
    soup = BeautifulSoup(res.text, 'html.parser')
    return soup
  else:
    return None

def createDic (ListOfString, ListOfInt3x):
    Dic = {}
    for i in range(1,len(ListOfString)):
        Dic[ListOfString[i]] = [ListOfInt3x[3*i-3] , ListOfInt3x[3*i-2] , ListOfInt3x[3*i-1]]
    return(Dic)

def getDataFrameforYear (Year):
    
    soup = getSoupFromURL('http://alize2.finances.gouv.fr/communes/eneuro/detail.php?icom=056&dep=075&type=BPS&param=5&exercice='+ Year)
    Montants = soup.find_all(class_ = "montantpetit G")
    IntituléMontants = soup.find_all(class_ = "libellepetit G")
    ListeIntituléMontants = list(map(lambda x: x.get_text(), IntituléMontants))
    ListeMontants = list(map(lambda x: int(x.get_text().replace(u'\xa0' or u' ', u'').replace(u' ' or u' ', u'')), Montants ))
    Dic = createDic(ListeIntituléMontants,ListeMontants)
    DataFrame = pd.DataFrame(Dic, index=['En milliers d Euros','Euros par habitant','Moyenne de la strate'])
    return(DataFrame)
    
getDataFrameforYear('2010')

,= Besoin ou capacité de financement de la section d'investissement = E,Besoin ou capacité de financement Résiduel de la section d'investissement = D - C,RESULTAT COMPTABLE = A - B = R,Résultat d'ensemble = R - E,TOTAL DES CHARGES DE FONCTIONNEMENT = B,TOTAL DES EMPLOIS D'INVESTISSEMENT = D,TOTAL DES RESSOURCES D'INVESTISSEMENT = C
En milliers d Euros,322767,2801912,4964789,325230,5425200,2479145,460411
Euros par habitant,146,1265,2241,147,2449,1119,208
Moyenne de la strate,146,1265,2241,147,2449,1119,208